In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("../csv_collection/data.csv",index_col = 0)
df.head()

,X,ind,X.Time,ACC001_X,ACC001_Y,ACC001_Z,ACC002_Z,ACC003_Z,CAC001,CAC002,...,WGT002_S,WGT002_V,WVR001_HDR,WVR001_HSP,WVR001_PDR,WVR001_PSP,WVR002_HDR,WVR002_HSP,WVR002_PDR,WVR002_PSP
1,2029,2029,2018-01-02 09:38:00.0000,40.805119,25.504034,0.416799,974.861377,1003.282507,712.910132,707.205802,...,1.813764,0.289230,7.401429,0.424711,116.731682,3.260048,89.110220,60.459179,272.565559,0.995250
7,2069,2069,2018-01-02 10:18:00.0000,40.827409,25.699538,0.758546,974.872434,1003.569013,712.738905,706.851693,...,1.606156,0.312017,14.887839,0.439992,147.398011,1.670779,89.241007,60.369046,261.912444,0.857520
8,2091,2091,2018-01-02 10:40:00.0000,40.807949,25.851085,0.664547,974.777937,1003.794401,712.730147,706.634184,...,0.955877,0.169726,9.712352,0.134816,198.366212,0.827321,89.370690,60.502694,280.931183,0.696128
15,2146,2146,2018-01-02 11:35:00.0000,40.980717,26.277307,1.573698,974.768914,1004.406324,712.621695,706.231516,...,2.585505,0.166486,16.055534,0.734244,296.837162,2.585418,88.674855,60.469280,93.611917,1.421831
16,2151,2151,2018-01-02 11:40:00.0000,40.993807,26.313338,1.639161,974.710911,1004.481729,712.663076,706.231409,...,1.925782,0.316285,10.667167,0.430964,280.470441,2.179158,88.331297,60.458463,98.351081,1.768940

In [8]:
# X, ind 굳이 불필요한 컬럼 제거
df.drop(columns = ['X','ind'], inplace = True)
df

,X.Time,ACC001_X,ACC001_Y,ACC001_Z,ACC002_Z,ACC003_Z,CAC001,CAC002,CAC003,CAC004,...,WGT002_S,WGT002_V,WVR001_HDR,WVR001_HSP,WVR001_PDR,WVR001_PSP,WVR002_HDR,WVR002_HSP,WVR002_PDR,WVR002_PSP
1,2018-01-02 09:38:00.0000,40.805119,25.504034,0.416799,974.861377,1003.282507,712.910132,707.205802,347.641772,378.303599,...,1.813764,0.289230,7.401429,0.424711,116.731682,3.260048,89.110220,60.459179,272.565559,0.995250
7,2018-01-02 10:18:00.0000,40.827409,25.699538,0.758546,974.872434,1003.569013,712.738905,706.851693,347.931524,378.772523,...,1.606156,0.312017,14.887839,0.439992,147.398011,1.670779,89.241007,60.369046,261.912444,0.857520
8,2018-01-02 10:40:00.0000,40.807949,25.851085,0.664547,974.777937,1003.794401,712.730147,706.634184,348.467358,379.236346,...,0.955877,0.169726,9.712352,0.134816,198.366212,0.827321,89.370690,60.502694,280.931183,0.696128
15,2018-01-02 11:35:00.0000,40.980717,26.277307,1.573698,974.768914,1004.406324,712.621695,706.231516,349.356274,380.201538,...,2.585505,0.166486,16.055534,0.734244,296.837162,2.585418,88.674855,60.469280,93.611917,1.421831
16,2018-01-02 11:40:00.0000,40.993807,26.313338,1.639161,974.710911,1004.481729,712.663076,706.231409,349.273731,380.100479,...,1.925782,0.316285,10.667167,0.430964,280.470441,2.179158,88.331297,60.458463,98.351081,1.768940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21009,2018-09-02 04:16:00.0000,46.574260,33.699470,16.597090,975.284800,1009.254000,713.935900,704.822700,352.251500,383.633000,...,5.473823,0.341042,34.600160,59.489550,43.875460,86.234510,19.305280,0.176356,220.942100,0.906738
21012,2018-09-02 04:26:00.0000,46.561680,33.689300,16.564040,975.311200,1009.257000,713.694300,704.636600,352.402900,383.641500,...,4.271715,0.352169,34.719680,59.636390,43.586400,86.062720,19.380030,0.154776,213.337100,0.926696
21014,2018-09-02 04:37:00.0000,46.550070,33.680960,16.523220,975.310900,1009.221000,713.844500,704.692900,352.246700,383.586700,...,4.580638,0.286272,34.608600,59.496650,43.752790,86.217590,15.701640,0.168793,243.926300,1.260860
21015,2018-09-02 04:39:00.0000,46.547640,33.680400,16.515360,975.286400,1009.191000,713.613700,704.438100,352.227600,383.714200,...,4.011181,0.348011,34.598510,59.484100,43.768790,86.231900,22.107270,0.165961,199.854800,0.730920
21016,2018-09-02 04:42:00.0000,46.545700,33.679320,16.508930,975.323700,1009.231000,713.583800,704.476900,352.198600,383.471100,...,4.512936,0.359723,34.594960,59.475220,43.748780,86.230460,14.243450,0.177368,136.903100,1.216474

In [11]:
## X.time을 datetime으로 변환
df['X.Time'] = pd.to_datetime(df['X.Time'])
df.head()

,X.Time,ACC001_X,ACC001_Y,ACC001_Z,ACC002_Z,ACC003_Z,CAC001,CAC002,CAC003,CAC004,...,WGT002_S,WGT002_V,WVR001_HDR,WVR001_HSP,WVR001_PDR,WVR001_PSP,WVR002_HDR,WVR002_HSP,WVR002_PDR,WVR002_PSP
1,2018-01-02 09:38:00,40.805119,25.504034,0.416799,974.861377,1003.282507,712.910132,707.205802,347.641772,378.303599,...,1.813764,0.289230,7.401429,0.424711,116.731682,3.260048,89.110220,60.459179,272.565559,0.995250
7,2018-01-02 10:18:00,40.827409,25.699538,0.758546,974.872434,1003.569013,712.738905,706.851693,347.931524,378.772523,...,1.606156,0.312017,14.887839,0.439992,147.398011,1.670779,89.241007,60.369046,261.912444,0.857520
8,2018-01-02 10:40:00,40.807949,25.851085,0.664547,974.777937,1003.794401,712.730147,706.634184,348.467358,379.236346,...,0.955877,0.169726,9.712352,0.134816,198.366212,0.827321,89.370690,60.502694,280.931183,0.696128
15,2018-01-02 11:35:00,40.980717,26.277307,1.573698,974.768914,1004.406324,712.621695,706.231516,349.356274,380.201538,...,2.585505,0.166486,16.055534,0.734244,296.837162,2.585418,88.674855,60.469280,93.611917,1.421831
16,2018-01-02 11:40:00,40.993807,26.313338,1.639161,974.710911,1004.481729,712.663076,706.231409,349.273731,380.100479,...,1.925782,0.316285,10.667167,0.430964,280.470441,2.179158,88.331297,60.458463,98.351081,1.768940

In [12]:
df.rename(columns = {'X.Time' : 'time'}, inplace = True)
df.head()

,time,ACC001_X,ACC001_Y,ACC001_Z,ACC002_Z,ACC003_Z,CAC001,CAC002,CAC003,CAC004,...,WGT002_S,WGT002_V,WVR001_HDR,WVR001_HSP,WVR001_PDR,WVR001_PSP,WVR002_HDR,WVR002_HSP,WVR002_PDR,WVR002_PSP
1,2018-01-02 09:38:00,40.805119,25.504034,0.416799,974.861377,1003.282507,712.910132,707.205802,347.641772,378.303599,...,1.813764,0.289230,7.401429,0.424711,116.731682,3.260048,89.110220,60.459179,272.565559,0.995250
7,2018-01-02 10:18:00,40.827409,25.699538,0.758546,974.872434,1003.569013,712.738905,706.851693,347.931524,378.772523,...,1.606156,0.312017,14.887839,0.439992,147.398011,1.670779,89.241007,60.369046,261.912444,0.857520
8,2018-01-02 10:40:00,40.807949,25.851085,0.664547,974.777937,1003.794401,712.730147,706.634184,348.467358,379.236346,...,0.955877,0.169726,9.712352,0.134816,198.366212,0.827321,89.370690,60.502694,280.931183,0.696128
15,2018-01-02 11:35:00,40.980717,26.277307,1.573698,974.768914,1004.406324,712.621695,706.231516,349.356274,380.201538,...,2.585505,0.166486,16.055534,0.734244,296.837162,2.585418,88.674855,60.469280,93.611917,1.421831
16,2018-01-02 11:40:00,40.993807,26.313338,1.639161,974.710911,1004.481729,712.663076,706.231409,349.273731,380.100479,...,1.925782,0.316285,10.667167,0.430964,280.470441,2.179158,88.331297,60.458463,98.351081,1.768940

## 1월 시각화

In [33]:
# 시간대별 데이터 개수
# 월별로 먼저 보자
## 1월
month_1 = df.loc[df['time'].dt.month == 1, :]
month_1.shape

(1005, 106)

In [ ]:
# 1월의 센서별 값 시계열 그래프


plt.figure(figsize = (12,6))
plt.plot(month_1['time'], month_1.values())